serde-api/src/main/java/io/micronaut/serde/AbstractStreamDecoder.java
serde-api/src/main/java/io/micronaut/serde/Decoder.java
serde-api/src/main/java/io/micronaut/serde/Deserializer.java
serde-api/src/main/java/io/micronaut/serde/UpdatingDeserializer.java
serde-api/src/main/java/io/micronaut/serde/annotation/Serdeable.java
serde-api/src/main/java/io/micronaut/serde/bind/SerdeJsonBeanPropertyBinderExceptionHandler.java
serde-api/src/main/java/io/micronaut/serde/deserializers/ObjectDeserializer.java
serde-api/src/main/java/io/micronaut/serde/exceptions/InvalidFormatException.java
serde-api/src/main/java/io/micronaut/serde/exceptions/InvalidPropertyFormatException.java
serde-api/src/main/java/io/micronaut/serde/exceptions/SerdeException.java
serde-api/src/main/java/io/micronaut/serde/util/JsonNodeDecoder.java
serde-bson/src/main/java/io/micronaut/serde/bson/BsonReaderDecoder.java
serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonDecoder.java
serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonJsonMapper.java
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/binding/JsonBeanPropertyBinderSpec.groovy
serde-jsonp/src/main/java/io/micronaut/serde/json/stream/JsonParserDecoder.java
src/main/docs/guide/quickStart.adoc

Support for BeanPropertyBinder

---

doc-examples/example-java/src/main/java/example/PointSerde.java
doc-examples/example-kotlin/src/main/kotlin/example/PointSerde.kt
serde-api/src/main/java/io/micronaut/serde/Decoder.java
serde-api/src/main/java/io/micronaut/serde/Encoder.java
src/main/docs/guide/serdes.adoc

Improvements encoder/decoder APIs to use try with resources

try-with-resources for encoder/decoder

---

serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java

Remove println

---

gradle.properties
settings.gradle.kts

Upgrade build, docs and Micronaut versions

bump versions

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonSerializeDeserializeSpec.groovy
serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeIntrospections.java

Fixes an issue when using JsonSerialize/Deserialize on interfaces implemented by subclasses found in the security module

Fix bug with JsonSerialize/Deserialize

---

serde-bson/build.gradle.kts
serde-bson/src/main/java/io/micronaut/serde/bson/AbstractBsonMapper.java
serde-bson/src/main/java/io/micronaut/serde/bson/BsonBinaryMapper.java
serde-bson/src/main/java/io/micronaut/serde/bson/BsonJsonMapper.java
serde-bson/src/main/java/io/micronaut/serde/bson/BsonWriterEncoder.java
serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonHttpCrudSpec.groovy
serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonMappingSpec.groovy
serde-bson/src/test/java/io/micronaut/serde/bson/Book.java
serde-support/src/main/java/io/micronaut/serde/support/util/BufferingJsonNodeProcessor.java

Fixes https://github.com/micronaut-projects/micronaut-data/issues/1295

fix java.lang.IllegalStateException: Read only 0 bytes!

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonManagedReferenceSpec.groovy
serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java

Fix backref/managedref with properties

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/object/ArraySerdeSpec.groovy
serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java

Allow serialization and deserializatin of object arrays

---

serde-jackson/build.gradle.kts
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/SerdeImportSpec.groovy
serde-support/src/main/java/io/micronaut/serde/support/serializers/SimpleObjectSerializer.java

Fix null handling in serde-imported classes with object arrays

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonUnwrappedSpec.groovy
serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java

This causes https://github.com/micronaut-projects/micronaut-problem-json/pull/196 to fail

Don't report an error when there is a collision with an ignored property with JsonUnwrapped

---

doc-examples/example-bson-java/build.gradle.kts
doc-examples/example-groovy/build.gradle
doc-examples/example-java/build.gradle.kts
doc-examples/example-jsonb-java/build.gradle.kts
doc-examples/example-kotlin/build.gradle.kts
serde-api/src/main/java/io/micronaut/serde/Deserializer.java
serde-api/src/main/java/io/micronaut/serde/SerdeJsonMapperSupplier.java
serde-api/src/main/java/io/micronaut/serde/SerdeRegistry.java
serde-api/src/main/java/io/micronaut/serde/Serializer.java
serde-api/src/main/resources/META-INF/services/io.micronaut.json.JsonMapperSupplier
serde-bson/build.gradle.kts
serde-jsonp/build.gradle.kts
serde-oracle-jdbc-json/build.gradle.kts
serde-support/build.gradle.kts
serde-support/src/main/java/io/micronaut/serde/support/DefaultDecoderContext.java
serde-support/src/main/java/io/micronaut/serde/support/DefaultEncoderContext.java
serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/CoreDeserializers.java

- add json mapper supplier
- progress Micronaut 4 snapshot upgrade

Implement changes required to upgrade to Micronaut 4 snapshot

---

gradle/libs.versions.toml
serde-api/src/main/java/io/micronaut/serde/config/SerdeConfiguration.java
serde-jackson/build.gradle.kts
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/BootstrapContextSpec.groovy
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/JsonCompileSpec.groovy
serde-tck/src/main/groovy/io/micronaut/serde/AbstractJsonCompileSpec.groovy
serde-tck/src/main/groovy/io/micronaut/serde/MockSerdeIntrospections.groovy

Fixes the error reported here https://ge.micronaut.io/s/pefm2573merk4/tests/:test-resources-hashicorp-vault:test/io.micronaut.testresources.hashicorp.vault.VaultStartedTest/initializationError?top-execution=1

Fix support for bootstrap context

---

settings.gradle.kts
src/main/docs/guide/introduction.adoc
src/main/docs/guide/introduction/why.adoc
src/main/docs/guide/quickStart/bsonQuick.adoc
src/main/docs/guide/quickStart/jacksonQuick.adoc
src/main/docs/guide/quickStart/jsonpQuick.adoc

Remove dependency substitutions from Micronaut Framework 4.0 documentation

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/object/EnumSerdeSpec.groovy
serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/serdes/EnumSerde.java

support enums with @JsonCreator

---

serde-api/src/main/java/io/micronaut/serde/ObjectMappers.java
serde-jsonp/src/main/java/io/micronaut/serde/json/stream/graalvm/JsonpFeature.java
serde-jsonp/src/main/resources/META-INF/native-image/io.micronaut.serde/micronaut-serde-jsonp/native-image.properties

the `@AutomaticFeature` annotation is deprecated

Remove use of AutomaticFeature

---

serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonJsonMapper.java

Also adds support for JsonSyntaxException.

Optimize JsonMapper.readValue(ByteBuffer, Argument)

---

serde-oracle-jdbc-json/src/main/java/io/micronaut/serde/oracle/jdbc/json/AbstractOracleJdbcJsonObjectMapper.java

Expose method in Oracle JDBC JSON implementation

---

serde-oracle-jdbc-json/src/main/java/io/micronaut/serde/oracle/jdbc/json/serde/OracleJsonLocaleTimeSerde.java
serde-oracle-jdbc-json/src/test/groovy/io/micronaut/serde/oracle/jdbc/json/OracleJdbcJsonBinaryBasicSerdeSpec.groovy
serde-oracle-jdbc-json/src/test/java/io/micronaut/serde/bson/SampleData.java

Missed adding this, found out during testing sample app.

Added missing LocalTime serde for Oracle Json

---

serde-processor/build.gradle.kts

See https://github.com/micronaut-projects/micronaut-validation/pull/96

Downgrade core processor dependency scope

---

serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/SimpleRecordLikeObjectDeserializer.java
serde-tck/src/main/groovy/io/micronaut/serde/AbstractBasicSerdeSpec.groovy
serde-tck/src/main/java/io/micronaut/serde/RecordBean.java

This fixes https://github.com/micronaut-projects/micronaut-security/pull/1194/files#r1182630762

Handle unknown properties for records

---

buildSrc/src/main/groovy/io.micronaut.build.internal.serde-examples.gradle
doc-examples/example-java/src/test/java/example/form/FormTest.java
gradle/libs.versions.toml
serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonDecoder.java
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/JacksonDecoderSpec.groovy

Decoding an object to a string doesn't throw an exception

---

serde-support/src/main/java/io/micronaut/serde/support/deserializers/ConvertibleValuesDeserializer.java
serde-support/src/test/groovy/io/micronaut/serde/support/deserializers/ConvertibleValuesDeserializerSpec.groovy

Should fix BookR2dbcSchemaMultiTenancySpec#testRest from https://github.com/micronaut-projects/micronaut-data/pull/2175

Implement ConvertibleValuesDeserializer

---

gradle/libs.versions.toml
serde-api/src/main/java/io/micronaut/serde/ObjectMapper.java

Moved to core JsonMapper. 
It updates to RC1 and platform M4

remove default methods

---

gradle/libs.versions.toml
serde-api/src/main/java/io/micronaut/serde/Deserializer.java
serde-api/src/main/java/io/micronaut/serde/config/DeserializationConfiguration.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/HealthResultDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/SimpleObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/SimpleRecordLikeObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/serdes/EnumSerde.java
settings.gradle.kts
test-suite/build.gradle.kts
test-suite/src/test/java/io/micronaut/serde/serdeimport/APIGatewayV2HTTPEventSerde.java
test-suite/src/test/java/io/micronaut/serde/serdeimport/ApiGatewayV2EventTest.java
test-suite/src/test/java/io/micronaut/serde/serdeimport/FileUtils.java
test-suite/src/test/resources/apiGatewayV2HTTPEvent.json

see: https://github.com/micronaut-projects/micronaut-aws/pull/1771

disable nullability strictness

---

serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
serde-support/src/test/groovy/io/micronaut/serde/support/deserializers/DeserializeSpec.groovy
serde-support/src/test/java/io/micronaut/serde/support/TestStatus.java

Fix for issue reported in data https://github.com/micronaut-projects/micronaut-data/issues/2403

Fix deserialization with nullable constructor argument of type Object

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonUnwrappedSpec.groovy
serde-jackson/src/test/java/io/micronaut/serde/jackson/nested/Address.java
serde-jackson/src/test/java/io/micronaut/serde/jackson/nested/Audit.java
serde-jackson/src/test/java/io/micronaut/serde/jackson/nested/CityData.java
serde-jackson/src/test/java/io/micronaut/serde/jackson/nested/NestedEntity.java
serde-jackson/src/test/java/io/micronaut/serde/jackson/nested/NestedEntityId.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/PropertiesBag.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java

@graemerocher Found one issue when field is marked `@NonNull` deserialization throws an error telling that field is required and not set, although it is set.
It seems like some nested objects are being processed more than once during deserializaiton.

Issue with @NonNull field in unwrapped class

---

serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonDecoder.java
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/JacksonDecoderSpec.groovy

Fix JacksonDecoder depth handling

---

gradle/libs.versions.toml

Bumps the core version to 4.1.7

Update to Micronaut Core 4.1.7

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonTypeInfoSpec.groovy
serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedObjectSerializer.java

Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/610

Correct polymorphism JsonTypeInfo

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonRootNameSpec.groovy
serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JsonRootNameMapper.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/WrappedObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedObjectSerializer.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/ObjectSerializer.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/SimpleObjectSerializer.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/WrappedObjectSerializer.java

Extracted wrapper serialize/deserializer into own classes

Support `JsonRootName`

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonTypeInfoSpec.groovy
serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java

Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/579

Fix subtypes without properties

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/CustomPrimitiveSerdeSpec.groovy
serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java

Find custom deserializer for a primitive type

---

gradle/libs.versions.toml
serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonBinaryBasicSerdeCompileSpec.groovy
serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonMappingSpec.groovy
serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonDecoder.java
serde-support/src/main/java/io/micronaut/serde/support/AbstractStreamDecoder.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/RuntimeTypeSerializer.java
serde-tck/src/main/groovy/io/micronaut/serde/AbstractBasicSerdeCompileSpec.groovy
test-suite-http-server-tck-netty/src/test/java/io/micronaut/serde/http/server/tck/netty/NettyHttpServerTestSuite.java

Unfortunately, this broke Micronaut Data Mongo integration. I need to think of another solution.

Revert "Allow to deserialize an empty string to null (#630)"

---

serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonMappingSpec.groovy
serde-bson/src/test/java/io/micronaut/serde/bson/Book.java
serde-bson/src/test/java/io/micronaut/serde/bson/BookWithConstructor.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
serde-tck/src/main/groovy/io/micronaut/serde/AbstractBasicSerdeSpec.groovy
serde-tck/src/main/java/io/micronaut/serde/BeanWithExtraMethod.java

Fixes problems with Micronaut Data

Fix constructor/bean properties and beans with an executable method

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonIgnoreAllowSpec.groovy
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonPropertyOrderSpec.groovy
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonTypeInfoSpec.groovy
serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java

Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/649

Fix ignore/exclude and order on a renamed property

---

serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonSubtypesSpec.groovy
serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonTypeInfoSpec.groovy
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonTypeInfoSpec.groovy
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonUnwrappedSpec.groovy
serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JsonTypeInfoMapper.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/WrappedArraySubtypedDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/ObjectSerializer.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/WrappedArraySerializer.java
src/main/docs/guide/jacksonAnnotations.adoc
test-suite-tck-jackson-databind/src/test/groovy/io/micronaut/serde/tck/jackson/databind/DatabindJsonTypeInfoSpec.groovy

Waiting for https://github.com/micronaut-projects/micronaut-serialization/pull/682 to be reviewed and merged

Support `@JsonTypeInfo(include = WRAPPER_ARRAY)`

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/SerdeImportSpec.groovy
serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java

Do you remember why you added this check @sdelamo?

Fix JsonProperty on mixin methods

---

serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonTypeInfoSpec.groovy
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonTypeInfoSpec.groovy
serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JsonTypeInfoMapper.java
serde-support/src/main/java/io/micronaut/serde/support/DefaultDecoderContext.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/deserializers/SubtypedExternalPropertyObjectDeserializer.java
serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
serde-support/src/main/java/io/micronaut/serde/support/util/SerdeArgumentConf.java
serde-support/src/main/java/io/micronaut/serde/support/util/SubtypeInfo.java
src/main/docs/guide/jacksonAnnotations.adoc

Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/321

Support `@JsonTypeInfo(include = EXTERNAL_PROPERTY)`

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonSerializeDeserializeSpec.groovy

I cannot reproduce the issue; it was probably fixed at some point.
Closes https://github.com/micronaut-projects/micronaut-serialization/issues/636

Add test for boxed/primitive deserializers

---

serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedMapSerializer.java
serde-support/src/test/groovy/io/micronaut/serde/support/serializers/ObjectWithMapSerializerSpec.groovy
serde-support/src/test/java/io/micronaut/serde/support/ObjectWithMap.java

Found this bug when tried to serialize object with the map

Fix customized map serializer

---

serde-jackson/src/test/groovy/io/micronaut/serde/jackson/SerdeImportSpec.groovy
serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java

Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/687

Correct property's generic parameters

---

doc-examples/example-groovy/build.gradle
doc-examples/example-java/build.gradle.kts
doc-examples/example-jsonb-java/build.gradle.kts
gradle/libs.versions.toml
serde-api/build.gradle.kts
serde-bson/build.gradle.kts
serde-jackson/build.gradle.kts
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JacksonConfigurationSpec.groovy
serde-jsonp/build.gradle.kts
serde-oracle-jdbc-json/build.gradle.kts
serde-processor/build.gradle.kts
serde-support/build.gradle.kts
serde-tck-tests/build.gradle.kts
serde-tck/build.gradle.kts
test-suite-http-server-tck-netty/build.gradle.kts
test-suite-tck-jackson-databind/build.gradle.kts

Update libs.
Fix test for windows.

Bringing build scripts to a single view.

---

serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonValueSpec.groovy
serde-support/src/main/java/io/micronaut/serde/support/serdes/EnumSerde.java

Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/754

Fix enums with `@JsonValue` on a field

---

serde-api/src/main/java/io/micronaut/serde/Decoder.java
serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonPropertySpec.groovy
serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonDecoder.java
serde-support/src/main/java/io/micronaut/serde/support/serdes/NumberTypeSerde.java
serde-support/src/main/java/io/micronaut/serde/support/serdes/Serdes.java

Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/570

Support decoding `Number`

---

serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonPropertySpec.groovy
serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonPropertySpec.groovy
serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
test-suite-tck-jackson-databind/src/test/groovy/io/micronaut/serde/tck/jackson/databind/DatabindJsonPropertySpec.groovy

Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/717

Correct ignored properties for a constructor injection

---

serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
serde-support/src/test/groovy/io/micronaut/serde/support/serdes/BeanContextSerdeSpec.groovy

Not sure of all the implications, but this fixes #792

fix(micronaut-serde-support): fix DefaultSerdeRegistry not retrieving EnumSerde
