- serde-api/src/main/java/io/micronaut/serde/Encoder.java
- serde-bson/src/main/java/io/micronaut/serde/bson/AbstractBsonMapper.java
- serde-bson/src/main/java/io/micronaut/serde/bson/BsonWriterEncoder.java
- serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonWriterEncoderSpec.groovy
- serde-jsonp/src/main/java/io/micronaut/serde/json/stream/JsonStreamEncoder.java
- serde-jsonp/src/test/groovy/io/micronaut/serde/json/stream/JsonStreamEncoderSpec.groovy
Path is calculated lazily because it's only needed for error messages. Using a reference to the parent encoder keeps memory use relatively low.
Resolves #60
Resolves #61
> Implement currentPath for jsonp and bson encoders

- serde-api/src/main/java/io/micronaut/serde/DefaultDecoderContext.java
- serde-api/src/main/java/io/micronaut/serde/DefaultEncoderContext.java
- serde-api/src/main/java/io/micronaut/serde/DefaultSerdeRegistry.java
- serde-api/src/main/java/io/micronaut/serde/Deserializer.java
- serde-api/src/main/java/io/micronaut/serde/NamingStrategyLocator.java
- serde-api/src/main/java/io/micronaut/serde/Serializer.java
- serde-api/src/main/java/io/micronaut/serde/annotation/Serdeable.java
- serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
- serde-api/src/main/java/io/micronaut/serde/config/naming/IdentityStrategy.java
- serde-api/src/main/java/io/micronaut/serde/config/naming/KebabCaseStrategy.java
- serde-api/src/main/java/io/micronaut/serde/config/naming/LowerCamelCaseStrategy.java
- serde-api/src/main/java/io/micronaut/serde/config/naming/LowerCaseStrategy.java
- serde-api/src/main/java/io/micronaut/serde/config/naming/LowerDotCaseStrategy.java
- serde-api/src/main/java/io/micronaut/serde/config/naming/PropertyNamingStrategy.java
- serde-api/src/main/java/io/micronaut/serde/config/naming/SnakeCaseStrategy.java
- serde-api/src/main/java/io/micronaut/serde/config/naming/UpperCamelCaseStrategy.java
- serde-api/src/main/java/io/micronaut/serde/config/naming/UpperCamelCaseStrategyWithSpaces.java
- serde-api/src/main/java/io/micronaut/serde/deserializers/DeserBean.java
- serde-api/src/main/java/io/micronaut/serde/serializers/SerBean.java
- serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonMappingSpec.groovy
- serde-bson/src/test/java/io/micronaut/serde/bson/NamingStrategiesEntity.java
- serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
If the naming strategy is not recognized or initialized it's remapped as a runtime naming strategy. It's also possible now to have per property naming strategies
> Runtime naming strategy

- serde-api/src/main/java/io/micronaut/serde/annotation/Serdeable.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/SerdeImportSpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/object/ObjectSerdeSpec.groovy
- serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
- serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeIntrospections.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/CoreDeserializers.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/ObjectSerializer.java
* If no introspection is present fallback to trying to resolve based on the runtime type
* `@Deserializable` should be annotated with `@Introspected`
* Allow deserializing raw maps
> Fix issues identified supporting problem/json

- serde-jackson/build.gradle.kts
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/JsonCompileSpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/SerdeImportSpec.groovy
- serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
- serde-processor/src/main/java/io/micronaut/serde/processor/jackson/databind/JsonDeserializeMapper.java
- serde-processor/src/main/java/io/micronaut/serde/processor/jackson/databind/JsonSerializeMapper.java
- serde-support/build.gradle.kts
- serde-support/src/main/java/io/micronaut/serde/support/AdditionalSerdes.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/ObjectSerializer.java
- serde-support/src/test/groovy/io/micronaut/serde/support/CoreTypeSerdeSpec.groovy
Changes to support deserialising HealthResult, not fully implemented because core doesn't support retrieving type level metadata from imported introspections
> Fixes HealthResult interface deserialization

- serde-processor/src/main/java/io/micronaut/serde/processor/bson/BsonDiscriminatorTransformer.java
- serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JsonCreatorMapper.java
- serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JsonIncludeMapper.java
- serde-processor/src/main/java/io/micronaut/serde/processor/jsonb/JsonbNillableTransformer.java
- serde-processor/src/main/java/io/micronaut/serde/processor/jsonb/JsonbPropertyTransformer.java
This avoids errors in the introspection when serde-api isn't present on the classpath at runtime. See https://github.com/micronaut-projects/micronaut-security/pull/889
> Generate lazy references to SerdeConfig enums

- serde-api/src/main/java/io/micronaut/serde/Deserializer.java
- serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonMappingSpec.groovy
- serde-bson/src/test/java/io/micronaut/serde/bson/QuantityAttributeConverter.java
- serde-bson/src/test/java/io/micronaut/serde/bson/Sale1.java
- serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/CoreDeserializers.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
BTW it might be a good idea to change the order of the parameters in `createSpecific` to have the same order as in `deserialize`: context and then the type, in the same way, `serialize` can have context, type, and then value.
> Add decoder context and argument type in `getDefault` method

- serde-api/src/main/java/io/micronaut/serde/config/DeserializationConfiguration.java
- serde-api/src/test/groovy/io/micronaut/serde/config/DeserializationConfigurationSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/config/SerdeJsonConfiguration.java
Javadoc says it defaults to 100 but the bean of type `DeserializationConfiguration` does not have any default value.
> add DeserializationConfiguration default value

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/object/ObjectSerdeSpec.groovy
> add test for #124

- serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonPropertySpec.groovy
- serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JsonPropertyMapper.java
- serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
This matches jackson behavior. There was previously an error trying to set primitives to `null`, this patch assigns them the default value, instead.
Also introduces support for `@JsonProperty(required=true)` to allow requiring primitive properties as well.
Fixes #169
> Do not require primitive constructor values by default

- gradle.properties
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonTypeInfoSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/serdes/CustomizedObjectArraySerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedObjectSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/ObjectSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
Use the runtime type if subtyping is involved or the type is abstract. Fixes #204
Also fixes #176
> Fix subtyping serialization

- serde-api/src/main/java/io/micronaut/serde/config/DeserializationConfiguration.java
- serde-api/src/main/java/io/micronaut/serde/config/SerializationConfiguration.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/BootstrapContextSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeIntrospections.java
- serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/CoreSerdes.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/ObjectSerializer.java
This patch adds a test for bootstrap compatibility, and adds `@BootstrapContextCompatible` to all necessary dependencies.
Fixes #238
> Make jackson JsonMapper available in boostrap context

- serde-api/build.gradle.kts
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/object/ObjectSerdeSpec.groovy
- serde-processor/build.gradle.kts
- serde-support/src/main/java/io/micronaut/serde/support/serdes/HealthStatusSerde.java
- serde-support/src/test/groovy/io/micronaut/serde/support/CoreTypeSerdeSpec.groovy
Test fails with: 
```
Condition failed with Exception:test io.micronaut.serde.jackson.object.ObjectSerdeSpec
writeJson(jsonMapper, beanUnderTest) == '{"foo":"bar"}'
|         |           |
|         |           <example.Test@190728b4 foo=bar>
|         <io.micronaut.serde.jackson.JacksonJsonMapper@4e6f9498 registry=io.micronaut.serde.support.DefaultSerdeRegistry@4a8375f9 deserializationConfig=io.micronaut.json.JsonStreamConfig@275581aa treeCodec=io.micronaut.jackson.core.tree.JsonNodeTreeCodec@da1056e objectCodecImpl=io.micronaut.serde.jackson.JacksonJsonMapper$ObjectCodecImpl@2c634771 view=class java.lang.Object encoderContext=io.micronaut.serde.support.DefaultSerdeRegistry$1@175b4fae decoderContext=io.micronaut.serde.support.DefaultSerdeRegistry$2@1c88d43e>
java.lang.ClassCastException: …
```
> test: annotate failing test with @PendingFeature

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/TokenErrorSpec.groovy
- serde-jackson/src/test/java/io/micronaut/serde/jackson/enumjsonvalue/TokenError.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/EnumSerde.java
see https://github.com/micronaut-projects/micronaut-serialization/issues/297
> Support more leniant enum parsing and support JsonValue on enum methods

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/BootstrapContextSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/CoreDeserializers.java
Without this change Vault fails to read keys when Micronaut Serialization is used
> Allow core deserializers to be used in bootstrap context

- serde-bson/src/main/java/io/micronaut/serde/bson/BsonReaderDecoder.java
- serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonReaderDecoderJsonSpec.groovy
The value of `currentToken` is used to read the next token. The MongoDB BSON reader consumes the full value and sets the internal state to TYPE. This change sets the `currentToken` to `null` so the next token can be read correctly
> Issue #371:  Sets the currentToken to null after skipping a value

- doc-examples/example-groovy/src/main/groovy/example/Person.groovy
- doc-examples/example-groovy/src/main/groovy/example/PersonFilter.groovy
- doc-examples/example-groovy/src/test/groovy/example/PersonFilterTest.groovy
- doc-examples/example-java/src/main/java/example/Person.java
- doc-examples/example-java/src/main/java/example/PersonFilter.java
- doc-examples/example-java/src/test/java/example/PersonFilterTest.java
- doc-examples/example-kotlin/build.gradle.kts
- doc-examples/example-kotlin/src/main/kotlin/example/Person.kt
- doc-examples/example-kotlin/src/main/kotlin/example/PersonFilter.kt
- doc-examples/example-kotlin/src/test/kotlin/example/PersonFilterTest.kt
- serde-api/src/main/java/io/micronaut/serde/PropertyFilter.java
- serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
- serde-jackson/src/main/java/io/micronaut/serde/jackson/SpecializedJacksonEncoder.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonFilterSpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonIncludeSpec.groovy
- serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
- serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JsonFilterMapper.java
- serde-processor/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationMapper
- serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedObjectSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/ObjectSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
- serde-tck/src/main/groovy/io/micronaut/serde/MockSerdeIntrospections.groovy
- src/main/docs/guide/jacksonAnnotations.adoc
- src/main/docs/guide/jacksonFilter.adoc
- src/main/docs/guide/toc.yml
Adds support for the [JsonFilter](https://fasterxml.github.io/jackson-annotations/javadoc/2.7/com/fasterxml/jackson/annotation/JsonFilter.html) annotation on types.
* The annotation seems to be only used during serialization, therefore deserialization is not modified.
* The annotation is allowed on properties but this wasn't implemented.
* [Jackson PropertyFilter](https://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/ser/PropertyFilter.html) can be used to filter out container elements. It wasn't implemented yet.
> Add property filter

- serde-bson/src/main/java/io/micronaut/serde/bson/BsonReaderDecoder.java
- serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonReaderDecoderJsonSpec.groovy
The value of `currentToken` is used to read the next token. The MongoDB BSON reader consumes the full value and sets the internal state to TYPE. This change sets the `currentToken` to `null` so the next token can be read correctly
(cherry picked from commit d874b7a9b93ceda9851872843bcbd9e40436968f)
NOTE: This has already been merged into `master` via #372 This is an attempt to get it into 1.5.1-SNAPSHOT build. (Sorry, I should have targeted this branch before)
> Issue #371:  Sets the currentToken to null after skipping a value (#372)

- serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonSubtypesSpec.groovy
- serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SubtypedDeserBean.java
- The `@JsonSubtypes.Type` names property is now used and merged with type name to be used for deserialization
- The name property is used even if the subtype has `@SerdeConfig` annotation (in previous behavior the subtype annotation wasn't visited and therefore name wasn't used)
- The `@JsonTypeName` is prioritized over `@JsonSubtypes.Type` name and names properties
Examples of jackson behavior in this tutorial: https://www.logicbig.com/tutorials/misc/jackson/json-type-info-with-logical-type-name.html
> Improve @JsonSubtypes Handling

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/object/EnumSerdeSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/serdes/EnumSerde.java
- serde-tck/src/main/groovy/io/micronaut/serde/AbstractJsonCompileSpec.groovy
- Backport #368.
- Add support for `null` values in the json creator and json value with enums.
- Extend the tests.
> JSON value and builder annotations support for enums for 1.5.x

- serde-oracle-jdbc-json/src/main/java/io/micronaut/serde/oracle/jdbc/json/OracleJdbcJsonTextObjectMapper.java
In situation when we have these two oracle json mappers `OracleJdbcJsonTextObjectMapper` and `OracleJdbcJsonBinaryObjectMapper` on the classpath and without micronaut-serde-jackson which defines primary `JsonMapper` then app is not able to resolve `JsonMapper` injection in some of the classes in micronaut-data so we can help this way, setting `OracleJdbcJsonTextObjectMapper` higher priority than `OracleJdbcJsonBinaryObjectMapper` and then make it default `JsonMapper`.
If there is some better solution for this case, please let me know and I will update this. Without this, in apps that include serde-oracle-jdbc-json we will have issues when single `JsonMapper` needs to be injected.
> Set OracleJdbcJsonTextObjectMapper higher priority than OracleJdbcJsonBinaryObjectMapper

- serde-api/src/main/java/io/micronaut/serde/config/SerdeConfiguration.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/DefaultFormattedTemporalSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/FormattedTemporalSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/InstantSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/LocalDateSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/LocalDateTimeSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/LocalTimeSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/NumericSupportTemporalSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/OffsetDateTimeSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/ZonedDateTimeSerde.java
- serde-support/src/test/groovy/io/micronaut/serde/support/serdes/InstantSerdeSpec.groovy
- serde-support/src/test/groovy/io/micronaut/serde/support/serdes/OffsetDateTimeSerdeSpec.groovy
- serde-tck/src/main/groovy/io/micronaut/serde/data/Users1.java
- serde-tck/src/main/groovy/io/micronaut/serde/data/Users2.java
- serde-tck/src/main/groovy/io/micronaut/serde/data/Users3.java
This PR reworks the handling for numeric values for parsing and writing java.time classes. The old handling was inconsistent (millis for Instant, ODT, ZDT, but nanos for LT), incomplete (no support for decimals), incompatible with jackson-databind (it uses seconds by default), and not configurable. It also used an "optimistic" decode pattern that broke #425.
These changes remove the old write-dates-as-timestamps setting and replace it with two new settings, time-write-shape and numeric-time-unit. The former controls the format to serialize as (number or string), the latter controls the time unit. The old behavior can be activated with:
```
micronaut.serde.time-write-shape=integer
micronaut.serde.numeric-time-unit=legacy
```
The defaults are to serialize as string by default, removing any …
> Rework numeric time handling

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/CustomStringSerdeSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/CoreDeserializers.java
- settings.gradle.kts
> Support custom serdes for builtin types

- serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonDecoder.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonGetterSetterSpec.groovy
The `JacksonDecoder.decodeKey` method relies on the `parser.currenName()` method. However, when reaching the end of a nested object, it seems to return the root key instead of `null` (for JSON `{"nested":{"a":"b"}}` after reading key `a` it would return `nested`). 
This only seems to happen when the next token was peeked and therefore happens in a specific test with `@JsonAnySetter`. (When the next toke is not peeked,  `JacksonDecoder.decodeKey` uses `parser.nextFieldName()` which has the desired behavior.
The issue is solved by explicitly verifying that we haven't parsed the whole object (next token is not `END_OBJECT`).
> Fix for JacksonDecoder.decodeKey returning key when there is none

- serde-api/src/main/java/io/micronaut/serde/Decoder.java
- serde-api/src/main/java/io/micronaut/serde/Encoder.java
- serde-api/src/main/java/io/micronaut/serde/config/SerdeConfiguration.java
- serde-api/src/main/java/io/micronaut/serde/util/BinaryCodecUtil.java
- serde-bson/src/main/java/io/micronaut/serde/bson/BsonReaderDecoder.java
- serde-bson/src/main/java/io/micronaut/serde/bson/BsonWriterEncoder.java
- serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonSpec.groovy
- serde-bson/src/test/java/io/micronaut/serde/bson/BinaryTypes.java
- serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonDecoder.java
- serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonEncoder.java
- serde-jsonp/src/main/java/io/micronaut/serde/json/stream/JsonStreamEncoder.java
- serde-oracle-jdbc-json/src/main/java/io/micronaut/serde/oracle/jdbc/json/OracleJdbcJsonGeneratorEncoder.java
- serde-oracle-jdbc-json/src/main/java/io/micronaut/serde/oracle/jdbc/json/OracleJdbcJsonParserDecoder.java
- serde-oracle-jdbc-json/src/main/java/io/micronaut/serde/oracle/jdbc/json/serde/OracleJsonBinarySerde.java
- serde-support/src/main/java/io/micronaut/serde/support/AbstractStreamDecoder.java
- serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
- serde-support/src/main/java/io/micronaut/serde/support/util/JsonNodeDecoder.java
- serde-support/src/main/java/io/micronaut/serde/support/util/JsonNodeEncoder.java
- serde-support/src/test/groovy/io/micronaut/serde/support/CoreTypeSerdeSpec.groovy
- serde-support/src/test/groovy/io/micronaut/serde/support/serdes/ByteArraySerdeSpec.groovy
jackson-databind writes byte[] as base64 and supports reading from base64 or array. Serde 2 writes byte[] as array, but does not support reading from base64, so prior to this change we are only compatible with jackson in one direction (serde encoder -> jackson decoder).
This patch adds decode support for base64, and for the bson binary type. For oracle jdbc json, a decodeBinary method already exists.
On the encode side, there is now a config flag to use format-specific byte array encoding, which is base64 for json. The default remains to write an array of numbers.
Fixes #520
> Support decoding base64 to byte[]

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonUnwrappedSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
I think this was missed, we should not add prop to write properties if it belongs to `@JsonUnwrapped` and was marked as read only.
> Field marked as READ_ONLY in JsonUnwrapped should not be writable

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonSubtypesSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
Because for WRAPPER_OBJECT the first objectDecoder is replaced, the first one is never finished.
Fixes #575
> Fix unnesting after WRAPPER_OBJECT subtype deserialization

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/builder/BuilderSpec.groovy
- serde-jackson/src/test/java/io/micronaut/serde/jackson/builder/TestBuildSubtype2.java
- serde-jackson/src/test/java/io/micronaut/serde/jackson/builder/TestBuildSupertype2.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
This fixes the combination of property-based subtyping and builders.
> Builder token buffer support

- buildSrc/src/main/groovy/io.micronaut.build.internal.serde-tck-suite.gradle
- gradle/libs.versions.toml
- serde-api/src/main/java/io/micronaut/serde/config/DefaultSerdeConfiguration.java
- serde-api/src/main/java/io/micronaut/serde/config/SerdeConfiguration.java
- serde-api/src/test/groovy/io/micronaut/serde/config/SerdeConfigurationSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/serdes/InetAddressSerde.java
- serde-support/src/test/groovy/io/micronaut/serde/support/serdes/InetAddressSerdeSpec.groovy
- serde-tck-tests/build.gradle.kts
- serde-tck-tests/src/main/java/io/micronaut/serde/tck/tests/InetAddressTest.java
- settings.gradle.kts
- test-suite-tck-jackson-databind/build.gradle.kts
- test-suite-tck-jackson-databind/src/test/java/io/micronaut/serde/tck/tests/jacksondatabind/SerializationJacksonDatabindSuite.java
- test-suite-tck-serde/build.gradle.kts
- test-suite-tck-serde/src/test/java/io/micronaut/serde/tck/tests/serde/SerializationSerdeSuite.java
This PR adds a tck so that we can compare Micronaut Serialization against Micronaut Jackson Databind
It adds a InetAddressSerde porting Jackson logic https://github.com/FasterXML/jackson-databind/blob/2.15/src/main/java/com/fasterxml/jackson/databind/ser/std/InetAddressSerializer.java
This is related to: https://github.com/micronaut-projects/micronaut-discovery-client/issues/517
> serialization TCK and InetAddress Serde

- gradle/libs.versions.toml
- settings.gradle.kts
- test-suite-http-server-tck-netty/build.gradle.kts
- test-suite-http-server-tck-netty/src/test/java/io/micronaut/serde/http/server/tck/netty/NettyHttpServerTestSuite.java
- test-suite-http-server-tck-netty/src/test/resources/META-INF/services/io.micronaut.http.tck.ServerUnderTestProvider
- test-suite-http-server-tck-netty/src/test/resources/logback.xml
see: https://github.com/micronaut-projects/micronaut-serialization/issues/616 and https://github.com/micronaut-projects/micronaut-core/pull/10023
> test: run http server tck against Micronaut Serialization Jackson

- serde-api/src/main/java/io/micronaut/serde/ObjectSerializer.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonUnwrappedSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SimpleObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SimpleRecordLikeObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedObjectSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/JsonValueSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/ObjectSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/RuntimeTypeSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/SimpleObjectSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/WrappedObjectSerializer.java
Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/263
> Support unwrapped subtype beans

- serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonIgnoreSpec.groovy
- serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JacksonIgnorePropertiesMapper.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SimpleRecordLikeObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
- Corrected `ignoreUnknown` for `JsonIgnoreProperties`
- Corrected  ignoring properties during the deserialization for `JsonIgnoreProperties`
- Fixed https://github.com/micronaut-projects/micronaut-serialization/issues/625
> Correct `JsonIgnoreProperties`

- gradle/libs.versions.toml
- serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonBinaryBasicSerdeCompileSpec.groovy
- serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonDecoder.java
- serde-support/src/main/java/io/micronaut/serde/support/AbstractStreamDecoder.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/RuntimeTypeSerializer.java
- serde-tck/src/main/groovy/io/micronaut/serde/AbstractBasicSerdeCompileSpec.groovy
- test-suite-http-server-tck-netty/src/test/java/io/micronaut/serde/http/server/tck/netty/NettyHttpServerTestSuite.java
Not sure if this is the best solution. Maybe it should be configurable?
Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/619
> Allow to deserialize an empty string to null

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonSubtypesSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeIntrospections.java
SerdeImport does not add the Serdeable.Deserializable stereotype so findSubtypeDeserializables would not include an imported type in the subtype listing. This PR overrides findSubtypeDeserializables to use isEnabledForDeserialization which handles import properly.
This is for #536, not sure it fixes the full issue though.
> Fix SerdeImport of subtypes

- serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonTypeInfoSpec.groovy
- serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
- serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JsonTypeInfoMapper.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DemuxingObjectDecoder.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SubtypedPropertyObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/util/JsonNodeDecoder.java
- serde-support/src/test/groovy/io/micronaut/serde/support/deserializers/DemuxingObjectDecoderSpec.groovy
- which allows for the deserializer to set the type discriminator as an ordinary property
> Support `@JsonTypeInfo(visible=true)`

- serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonIgnoreAllowSpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonNamingSpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonTypeInfoSpec.groovy
- serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
- serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JacksonIgnorePropertiesMapper.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DemuxingObjectDecoder.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/581
Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/550
> Support `@JsonIgnoreProperties(allowGetters,allowSetters)`, align with Jackson behaviour

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonSerializeDeserializeSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/635
> Support `@Serdeable.Deserializable(as = ...)` on properties

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/SerdeImportSpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonGetterSetterSpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonSerializeDeserializeSpec.groovy
- serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
+ Refactored `SerdeAnnotationVisitor` to throw an exception instead of registering a failure 
Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/642
> Correct validation for `@Serializable(as = ...)` and `@Deserializable(as = ...)`

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonIgnoreAllowSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBeanKey.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserializationSerdeArgumentConf.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SubtypeInfo.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/ObjectSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/RuntimeTypeSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBeanKey.java
- serde-support/src/main/java/io/micronaut/serde/support/util/SerdeArgumentConf.java
Now, the leveled prefix/suffix are passed by extending the argument metadata. 
While fixing it, I discovered our key for maps of `DeserBean`/`SerBean` doesn't include annotations, and that can lead to one argument configuration being used for another one.
> Fix requirement to access `ObjectSerializer` and incorrect caching argument `DeserBean`/`SerBean`

- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DemuxingObjectDecoder.java
- serde-support/src/test/groovy/io/micronaut/serde/support/deserializers/DemuxingObjectDecoderSpec.groovy
Fixes https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/658
> Fix consuming null in `DemuxingObjectDecoder`

- serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
- serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonTypeInfoSpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonTypeInfoSpec.groovy
- serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
- serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JsonTypeInfoMapper.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SimpleObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SubtypedPropertyObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
- src/main/docs/guide/jacksonAnnotations.adoc
Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/664
> Support `@JsonTypeInfo(include = EXISTING_PROPERTY)`

- serde-api/src/main/java/io/micronaut/serde/Deserializer.java
- serde-api/src/main/java/io/micronaut/serde/ObjectMapper.java
- serde-api/src/main/java/io/micronaut/serde/SerdeRegistry.java
- serde-api/src/main/java/io/micronaut/serde/Serializer.java
- serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonJsonMapper.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/ConfigCloneSpec.groovy
- serde-jsonp/src/main/java/io/micronaut/serde/json/stream/JsonStreamMapper.java
- serde-support/src/main/java/io/micronaut/serde/support/DefaultDecoderContext.java
- serde-support/src/main/java/io/micronaut/serde/support/DefaultEncoderContext.java
- serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBeanKey.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/DefaultFormattedTemporalSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/InetAddressSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/InstantSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/LocalDateSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/LocalDateTimeSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/LocalTimeSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/OffsetDateTimeSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/ZonedDateTimeSerde.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/ObjectSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/OptionalMultiValuesSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBeanKey.java
This new method allows creating modified ObjectMappers with different configuration. This is required so that we can create an ObjectMapper using the BeanContext in micronaut-oraclecloud, which requires non-default serde configuration.
The changes here are a bit painful. The existing use sites of the config classes all assume the configuration is global and static. They all had to be adjusted.
The API is also painful to use because the configuration classes are interfaces. ConfigCloneSpec shows an example how to use this API without having to implement SerdeConfiguration and friends manually, but it's a bit awkward.
> Add ObjectMapper.cloneWithConfiguration

- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonSerializeDeserializeSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/CoreCollectionsDeserializers.java
- serde-support/src/main/java/io/micronaut/serde/support/serdes/CoreSerdes.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/CoreSerializers.java
- serde-support/src/main/java/io/micronaut/serde/support/serializers/OptionalSerializer.java
- serde-support/src/main/java/io/micronaut/serde/support/util/MatchArgumentQualifier.java
- serde-support/src/test/groovy/io/micronaut/serde/util/MatchArgumentSpec.groovy
- serde-tck/src/main/groovy/io/micronaut/serde/AbstractBasicSerdeCompileSpec.groovy
Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/690
> Implement correct generic arguments matcher

- serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonBinaryBasicSerdeCompileSpec.groovy
- serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonBinaryBasicSerdeSpec.groovy
- serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonBinarySpec.groovy
- serde-jackson/build.gradle.kts
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/http/Api.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/http/ApiClient.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/http/ApiController.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/http/ApiSpec.groovy
- serde-oracle-jdbc-json/src/test/groovy/io/micronaut/serde/oracle/jdbc/json/OracleJdbcJsonBinaryBasicSerdeSpec.groovy
- serde-tck/src/main/groovy/io/micronaut/serde/AbstractBasicSerdeSpec.groovy
- serde-tck/src/main/java/io/micronaut/serde/ApiResponse.java
- serde-tck/src/main/java/io/micronaut/serde/Dummy.java
Adds tests to validate that https://github.com/micronaut-projects/micronaut-serialization/pull/743 fixed more nested usecases
Closes https://github.com/micronaut-projects/micronaut-serialization/issues/413
> Add tests for nested serialization / deserialization

- serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonPropertySpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/SerdeImportSpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonPropertySpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
- serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
Add a test that https://github.com/micronaut-projects/micronaut-serialization/issues/402 is working.
Closes https://github.com/micronaut-projects/micronaut-serialization/issues/402
> Small improvements, refactoring + more tests

- serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonSerializeDeserializeSpec.groovy
- serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeIntrospections.java
Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/774
> Support referencing self in serialize/deserialize as

- serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonJsonMapper.java
- serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonObjectMapper.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/ConfigCloneSpec.groovy
Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/170
> Allow to clone `JacksonJsonMapper` with a different `SerdeJacksonConfiguration`

- serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonPropertySpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/SerdeImportSpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonPropertySpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/serdeimport/JodaDateTimeSerde.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/serdeimport/ResponseElementsEntitySerde.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/serdeimport/S3EventNotificationSerde.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/serdeimport/S3EventNotificationSpec.groovy
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/serdeimport/S3EventSerde.java
- serde-jackson/src/test/groovy/io/micronaut/serde/jackson/serdeimport/S3ObjectEntitySerde.java
- serde-jackson/src/test/resources/s3-event.json
- serde-jackson/src/test/resources/s3-put.json
- serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
FYI @sdelamo This now allows us to eliminate custom bean context deserializers https://github.com/micronaut-projects/micronaut-aws/blob/master/aws-lambda-events-serde/src/main/java/io/micronaut/aws/lambda/events/serde/ResponseElementsEntitySerde.java
> Support renaming constructor arguments and choosing a different constructor by mixins
